### ISSUE TITLE
Error: No authentication found

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#74]
Error: No authentication found
    at noAuthReject (/workspace/node_modules/@ecomplus/application-sdk/lib/methods/get-auth.js:17:21)
    at /workspace/node_modules/@ecomplus/application-sdk/lib/methods/get-auth.js:75:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {..

**Comment by matheusgnreis** [comment]
Possivelmente isso gerando alguns problemas relacionados a callback de loja https://github.com/ecomplus/app-bling-erp/blob/master/functions/routes/bling/callback.js#L34

**Comment by leomp12** [comment]
Tá rolando outros webhooks e callbacks normalmente então a priori não sei se tem um erro aí mesmo ou se de fato o Bling enviou requests aí de uma loja que não tem (pelo menos não mais) o app instalado, aí realmente não encontraria a autenticação e não seria um erro...
Tem que adicionar o store ID no log do erro lá pelo menos...
